# Normal keyboard orientation is when
# buttons are on the left side and knobs are on the right.
# However, you may want to use the keyboard in another orientation.
# To avoid remapping button positions in your head, just set it here.
# Possible values are:
#   (horizontal)
#   - 'normal': buttons on the left, knobs on the right
#   - 'upsidedown': buttons on the right, knobs on the left
#   (vertical)
#   - 'clockwise': buttons on the top, knobs on the bottom
#   - 'counterclockwise': buttons on the bottom, knobs on the top
orientation: normal

# Different keyboard models have different numbers of buttons and knobs.
# Set it here for proper handling.
# Count rows and columns with the keyboard in normal orientation (knobs on the right)
rows: 3
columns: 4
knobs: 2

# Layers are sets of alternative key mappings.
# The current layer is changed using a button on the side of the keyboard
# and displayed with LEDs on top (only for the moment of changing).
# All keyboards I saw had three layers, but I suppose other variants exist.
layers:
  - buttons:
      # Array of buttons.
      # In horizontal orientations it's `rows` rows `columns` buttons each.
      # In vertical: `columns` rows `rows` buttons each.
      # Each entry is either a sequence of 'chords' or a mouse event.
      # A chord is a combination of one key with optional modifiers,
      # like 'b', 'ctrl-alt-a' or 'win-rctrl-backspace'.
      # It can also be just modifiers without a key: 'ctrl-alt'.
      # You may combine up to 5 chords into a sequence using commas: 'ctrl-v,ctrl-c'.
      # Arbitrary HID usage codes (decimal) may be given like this: '<101>'.
      # See https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf (section 10)
      # for HID usage code list.
      - ["ctrl-alt-shift-f1", "ctrl-alt-shift-f2", "ctrl-alt-shift-f3", "ctrl-alt-shift-f4"]
      - ["alt", "tab", "ctrl-pageup", "ctrl-pagedown"]
      - ["win-space", "printscreen", "ctrl-alt-shift-d", "ctrl-alt-shift-m"]
    knobs:
      # Knobs are listed from left to right if horizontal.
      # Knobs are listed from top to bottom if vertical.
      # Knobs can be rotated counter-clockwise (ccw) or clockwise (cw)
      # and pressed down.
      - ccw: "ctrl-numpadminus"
        press: "ctrl-0"
        cw: "ctrl-numpadplus"
      - ccw: "volumedown"
        press: "mute"
        cw: "volumeup"

  - buttons:
      # Mouse events are clicks ('click/lclick', 'rclick', 'mclick') or
      # wheel events ('wheelup', 'wheeldown') with one optional modifier,
      # only 'ctrl', 'shift' and 'alt' are supported ('ctrl-wheeldown').
      # Clicks may combine several buttons, like this: 'click+rclick'.+
      - ["ctrl-shift-e", "ctrl-shift-f", "ctrl-f", "ctrl-p"]
      - ["alt", "tab", "ctrl-pageup", "ctrl-pagedown"]
      - ["win-space", "printscreen", "ctrl-shift-7", "ctrl-"]
    knobs:
      - ccw: "ctrl-numpadminus"
        press: "ctrl-0"
        cw: "ctrl-numpadplus"
      - ccw: "volumedown"
        press: "mute"
        cw: "volumeup"

  - buttons:
      # Multimedia commands are supported but
      # cannot be mixed with normal keys and modifiers.
      - ["ctrl-shift-e", "ctrl-shift-f", "ctrl-f", "ctrl-shift-g"]
      - ["alt", "tab", "ctrl-pageup", "ctrl-pagedown"]
      - ["win-space", "printscreen", "ctrl-c", "ctrl-v"]
    knobs:
      - ccw: "ctrl-numpadminus"
        press: "ctrl-0"
        cw: "ctrl-numpadplus"
      - ccw: "volumedown"
        press: "mute"
        cw: "volumeup"
